version: "2"
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gocyclo
    - dupl

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 150  # Allow more duplication in test code

issues:
  exclude-use-default: false
  max-same-issues: 0
  exclude-rules:
    - path: internal/utils/branch.go
      linters:
        - revive
      text: "var-naming: avoid meaningless package names"
